### ISSUE TITLE
how to create tables in sqlserver?

### ISSUE THREAD

**Issue by RocherKong** [grandchamp/Identity.Dapper#15]
I'm confused about the tables in DBMS.
for example,if I want to implete the dapperidentity on the sqlserver ,how can I initalize the sqlserver? is there some sql-scripts to execute? and if has ,how to get the script?

**Comment by grandchamp** [comment]
https://github.com/grandchamp/Identity.Dapper/blob/master/IdentityTablesSqlServer.sql

**Comment by RocherKong** [comment]
ok，thankyou.
