### ISSUE TITLE
PostgreSqlConfiguration.cs default schema

### ISSUE THREAD

**Issue by Helika0n** [grandchamp/Identity.Dapper#27]
Hello guys,

I'm new to the .Net world so I might have missed something,

Can we discuss the choice of "dbo" as a default schema for postgres? 
Shouldn't it be "public" instead as it is afaik the most common schema used for pgsql?

![image](https://cloud.githubusercontent.com/assets/10882699/24365742/3ef26c04-1317-11e7-8de0-5d368388fdd3.png)

Maybe it would be nice to have the opportunity to change it in any way, Sorry for the inconvenience if this is already possible but didn't found the way to do it.

**Comment by grandchamp** [comment]
You can use `AddDapperIdentityForPostgreSql(PostgreSqlConfiguration)` and change the `SchemaName` property.

**Comment by Helika0n** [comment]
Thanks !
