### ISSUE TITLE
UserManager + UserStore Interaction Issue

### ISSUE THREAD

**Issue by wapplegate** [grandchamp/Identity.Dapper#28]
I've been working on an implementation of the user and roles stores myself using Dapper and looking at your implementation I noticed something that you might want to think about. 

For example in your DapperUserStore class you have the AddToRole method. Within that you call this method:

`var result = await _userRepository.AddToRole(user.Id, roleName, cancellationToken, _transaction);`

That method will get the ID associated to the roleName provided and insert a new record associating the role to the user ID. Works fine. The issue is the way that the ASP.NET Core Identity UserManager class handles this. Take a look at this method found in the UserManager class:

```
public virtual async Task<IdentityResult> AddToRoleAsync(TUser user, string role)
{
    ThrowIfDisposed();
    var userRoleStore = GetUserRoleStore();
    if (user == null)
    {
        throw new ArgumentNullException(nameof(user));
    }

    var normalizedRole = NormalizeKey(role);
    if (await userRoleStore.IsInRoleAsync(user, normalizedRole, CancellationToken))
    {
        return await UserAlreadyInRoleError(user, role);
    }
    //  Your implementation of this method is called.
    await userRoleStore.AddToRoleAsync(user, normalizedRole, CancellationToken);
    // Then the update user method is called.
    return await UpdateUserAsync(user);
}
```
Essentially what will happen is your user repository method will be called to add the role and then the UserManager class will call UpdateUserAsync needlessly, because you handled associating the role already. This situation will happen in quite a few places when using the UserManager. The design the Identity Core folks are going for is to make all changes to the User entity and let the UpdateUserAsync method (which calls your UserStore UpdateAsync method) to do all the work.

I haven't totally gone over all the code in your repository, so maybe you've taken this into account already, but a lot of calls to the UserManager class will result extraneous Updates that aren't required. Not a major issue, but can hurt performance.

**Comment by ghidello** [comment]
I was wandering basically the same thing while i was searching the web for dapper implementations taking into consideration that the current asp.net identity implementation is based on the unit of work pattern. As explained pretty well in this [issue](https://github.com/aspnet/Identity/issues/1113), many methods are updating the in-memory User data, perform a final user validation and then persist all the data at the end. There are edge cases when, not following the unit of work, you may end up changing the data for a different user then the expected, again as explained in the mentioned issue. As @Singularity222, I'd like to know if these issues have been taken into account.

**Comment by wapplegate** [comment]
Take a look at this:

https://github.com/Singularity222/Manticore/blob/master/src/Manticore/User/UserRepository.cs

That's the UserRepository implementation I've created to be used with identity core. At the moment it supports roles and claims for a user. Everything is handled by the Update method. No need to call other methods. My implementation doesn't support transactions yet because I have an application wide plan for that. It could be a good basis for you though. Feel free to fork that repo and take a look at all the identity related code. Currently, that library as a ton of unrelated code in it as it's a personal project for myself. 

Also, I noticed in your UserRepository implementation you inject the RoleRepository class. I would not do that. If you need to use the RoleRepository and UserRepository it should be done in the UserStore implementation.

**Comment by grandchamp** [comment]
I don't call `UpdateUserAsync` on every calls like the original Identity. This method just updates the `User` entity fields.

**Comment by wapplegate** [comment]
You might not call it, but the identity methods do. That's the issue.
