### ISSUE TITLE
What is not ready yet ?

### ISSUE THREAD

**Issue by gtzinos** [grandchamp/Identity.Dapper#29]
Hello,
Thank you very much for your great job, i am not currently used it, but i will soon. I am developing a .net core api 1.1 app and i use Dapper with a mysql connector instead of Entity Framework. I search for 4 days for a similar project. What is not ready yet to use it?

**Comment by grandchamp** [comment]
I don't know if someone is using it on production yet. I've not covered all tests and there are some bugs laying around waiting for someone to find.
That's why.

**Comment by gtzinos** [comment]
Oh ok. I try to create something similar and i face some issues. If it just works it is a good step to use it. I tryied to build your code but i face exceptions like it doesn't find some imports from an absolute path. I removed all of your imports but any progress.
