### ISSUE TITLE
not an issue only a question

### ISSUE THREAD

**Issue by eld1887** [grandchamp/Identity.Dapper#30]
At the sample web Implementation you add  at the CustomUser the filed address.  Is it right that a column address is automatically creates at the database? I need some more column at the MysQl database  and i´m not sure if i add the columns per hand in that MySql file: https://github.com/grandchamp/Identity.Dapper/blob/master/IdentityTablesMySql.sql or if your code does it for me.

p.s:
but I get an error if i try to implement the IdentityTablesMySql.sql at my MySql server (which is outside of my Identity project). I get the error message: ERROR 1215 (HY000) at line 10: Cannot add foreign key constraint

Thanks for answer

**Comment by grandchamp** [comment]
All changes in columns/tables need to be done manually. Different from Migrations, my code don't create it automatically.
