### ISSUE TITLE
Missing JOIN criterion on GetRolesByUserIdQuery string.

### ISSUE THREAD

**Issue by steine** [grandchamp/Identity.Dapper#32]
(SqlServer)
Old:
* Returned all roles on all users that had a role.
"SELECT Name FROM %SCHEMA%.%ROLETABLE%, %SCHEMA%.%USERROLETABLE% WHERE UserId = %ID%";

New:
"SELECT Name FROM %SCHEMA%.%ROLETABLE%, %SCHEMA%.%USERROLETABLE% WHERE %SCHEMA%.%ROLETABLE%.Id = %SCHEMA%.%USERROLETABLE%.RoleId AND %SCHEMA%.%USERROLETABLE%.UserId = %ID%";

Only started testing so might find more.

**Comment by grandchamp** [comment]
Can you send a PR for this?

**Comment by grandchamp** [comment]
Thanks!
