### ISSUE TITLE
Integration tests

### ISSUE THREAD

**Issue by grandchamp** [grandchamp/Identity.Dapper#36]
Since much of the problems are related to raw queries, i think the best way to test is creating a integration tests project.
I'll start working on .NET Core 2.0 branch.

**Comment by grandchamp** [comment]
@steine check the core2.0 branch. I've added a simple integration test.

**Comment by steine** [comment]
Nice, I'll look into it.

**Comment by grandchamp** [comment]
Created all integration tests, integrating with Travis and merged to master.
