### ISSUE TITLE
ExternalLogin issues

### ISSUE THREAD

**Issue by sazmer** [grandchamp/Identity.Dapper#38]
I just managed to setup external login with Google. Ran into a few issues:

1. /src/Identity.Dapper/Extensions/SqlQueryParametersExtensions.cs
```
public static string SelectFilterWithTableName(this IEnumerable<string> propertyNames, string tableName)
        {
            var propertyNamesArray = propertyNames.ToArray();
 
            var filterBuilderArray = new List<string>(propertyNamesArray.Length);

            for (int i = 0; i < propertyNamesArray.Length; i++)
```
The line below added \" to propertynames, allthough the propertyNamesArray already contained "propertyName". Deleting them here fixed it for me, I dont know if it really should be changed somewhere else instead?

```
                filterBuilderArray.Add($"\"{tableName}\".{propertyNamesArray[i]}");


            return string.Join(", ", filterBuilderArray);
        }
```
2. 
The file /src/Identity.Dapper.SqlServer/Models/SqlServerConfiguration.cs
GetUserLoginByLoginProviderAndProviderKeyQuery = "SELECT TOP 1 %USERFILTER% FROM %SCHEMA%.%USERTABLE%, %SCHEMA%.%USERLOGINTABLE% WHERE LoginProvider = %LOGINPROVIDER% AND ProviderKey = %PROVIDERKEY%";

So I changed it to
GetUserLoginByLoginProviderAndProviderKeyQuery = "SELECT TOP 1 %USERFILTER% FROM %SCHEMA%.%USERTABLE%, %SCHEMA%.%USERLOGINTABLE% WHERE  %SCHEMA%.%USERTABLE%.Id = %SCHEMA%.%USERLOGINTABLE%.UserId AND LoginProvider = %LOGINPROVIDER% AND ProviderKey = %PROVIDERKEY%"; to get it working.

Don't have the skillz to make changes and PR, so hoping someone else will. Sorry :)

**Comment by grandchamp** [comment]
I'll take a look into it. Sorry for the late.

**Comment by grandchamp** [comment]
I need some help to understand 1st problem.
- Which method called ```SelectFilterWithTableName```?
- Which version are you using?
- Which DBMS are you using?

**Comment by sazmer** [comment]
MSSQL. Core 1.1.
In the UserRepository there are 3 functions that use a %USERFILTER% in the sql query to filter out the column names that should be added to the selected user. The userfilter is setup by calling SelectFilterWithTableName on userProperties in these functions:
```
public async Task<TUser> GetByUserLogin(string loginProvider, string providerKey)
public async Task<IList<TUser>> GetUsersByClaim(Claim claim)
public async Task<IList<TUser>> GetUsersInRole(string roleName)
```

They all produce the same error since they all use the same method of setting up the userfilter:
```
var defaultUser = Activator.CreateInstance<TUser>();
var userProperties = defaultUser.GetType().GetPublicPropertiesNames(y => !y.Name.Equals("ConcurrencyStamp")  && !y.Name.Equals("Id"));
userProperties.SelectFilterWithTableName(_sqlConfiguration.UserTable)
```

There is however a line to add the "" to the userproperties in these 3 functions:
 ```
if (_sqlConfiguration.UseQuotationMarks)
                        userProperties = userProperties.Select(y => string.Concat("\"", y, "\""));
```
but I can't really understand the logic since SelectFilterWithTableName isn't checking for this and just adding the quotationmarks again. Maybe I'm just not getting the code.

**Comment by grandchamp** [comment]
Did you tested with the latest source code version?
None of the integration tests show me an error on these functions, neither i could reproduce.

**Comment by sazmer** [comment]
I'm using 0.4.1-alpha. If I try to up to sqlserver version 0.5.0-alpha I have to upgrade to core2.0 aswell right? 
Trying to stick with the stable version.

**Comment by grandchamp** [comment]
With .NET Core 2.0 stable, did you migrated?

**Comment by sazmer** [comment]
I tried, ran into some real issues with VS for Mac though and haven't been able to do any work on my project at all. I'll make a fresh install and update.

**Comment by grandchamp** [comment]
Ok, i'll be waiting for your feedback, but i think it's all ok now.

**Comment by sazmer** [comment]
Finally got VS working with core 2.0.
I can confirm that the issue is gone in the version, good job!
