### ISSUE TITLE
services.AddIdentity in .net core 2.0

### ISSUE THREAD

**Issue by nyghtrocker** [grandchamp/Identity.Dapper#42]
Hi, 
AddDapperIdentityForSqlServer() is not working in .net core 2.0. I'm getting this error 
Reference to type 'IdentityBuilder' claims it is defined in 'Microsoft.AspNetCore.Identity', but it could not be found.I updated my project to .net core 2.0 and now having problem with AddDapperIdentityForSqlServer is not available in Startup.cs. Do you know how can I fix this?

**Comment by pmezykowski** [comment]
I had the same problem.
When I've updated Identity.Dapper (on local) to stable dotnet core 2.0 it started to work again.
@grandchamp please check my Pull Request (https://github.com/grandchamp/Identity.Dapper/pull/43)

**Comment by nyghtrocker** [comment]
Hi, I'm using Identity.Dapper -Version 0.5.0-alpha nuget package.Do you have any plan to update the nuget package?

**Comment by grandchamp** [comment]
Hey guys, tomorrow i'll upgrade the package with the PR sent.

**Comment by nyghtrocker** [comment]
Hi, If possible please update the package. I will be very grateful to you.

**Comment by grandchamp** [comment]
It should list in some minutes on NuGet.

**Comment by grandchamp** [comment]
@nyghtrocker all ok now?

**Comment by nyghtrocker** [comment]
Thanks for the updates and  It's working great

**Comment by grandchamp** [comment]
Nice to hear.
I'm thinking to release 1.0 version as is.

**Comment by nyghtrocker** [comment]
Ok, it will be good to have a release 1.0
