### ISSUE TITLE
How are you generating AES256 key and init vector?

### ISSUE THREAD

**Issue by sla1k** [grandchamp/Identity.Dapper#44]
I try using openssl for encrypt my DB pass with command:
`enc -aes256 -nosalt -k password -P`

And my output key and iv:
key=5F4DCC3B5AA765D61D8327DEB882CF992B95990A9151374ABD8FF8C5A7A0FE08
iv =B7B4372CDFBCB3D16A2631B59B509E94

After encode to Base64 I get strings twice as long, than in your sample.

What am I doing wrong?

**Comment by sla1k** [comment]
Damn, I'm idiot -_-
I convert string, not bytes.

**Comment by sla1k** [comment]
Which format for password must be and how generate it?

**Comment by grandchamp** [comment]
The password is your choice.
This behavior is just for secure sensitive information, like DB password.

**Comment by sla1k** [comment]
I mean  DB pass in DapperIdentity:Password, or it's pass not ecrypt?

**Comment by grandchamp** [comment]
You can pass it in plain text too, no problems.

**Comment by sla1k** [comment]
If I insert password like a plain text in settings without encrypt, I have this exception:
The input data is not a complete block.

**Comment by sla1k** [comment]
If I encrypt DB pass I have that strange UTF8 string
\u000e�\u0012����~���Oz��\v

**Comment by sibstark** [comment]
Hello. I have the same problem. I tooke a sample password 123456 from example and then i encrypted with help openssl  enc -aes256 -nosalt -k 123456 -P and got results
key=E10ADC3949BA59ABBE56E057F20F883E65B4AD270B3B98098D256AB32F5B8FBA
iv =9490B8780B1986D7196037E837C09F16
but after convert to Base64string i got key=RTEwQURDMzk0OUJBNTlBQkJFNTZFMDU3RjIwRjg4M0U2NUI0QUQyNzBCM0I5ODA5OEQyNTZBQjMyRjVCOEZCQQ==
iv=OTQ5MEI4NzgwQjE5ODZENzE5NjAzN0U4MzdDMDlGMTY=
these results are wrong. Can you provide in C# code how i can convert to bas64string those codes?
Thank you!
