### ISSUE TITLE
Sample Website Doesn't work

### ISSUE THREAD

**Issue by Bojanema** [grandchamp/Identity.Dapper#46]
Hello,

I'm trying to use this project, however, when I download the whole thing and I try to use the sample project, it doesn't work out of the box.  I wanted to make a suggestion for the sample project to be configured so that it will work on any machine when downloaded.

I didn't have time to dive in depth and figure out what exactly is wrong, but one of the errors I get is:

Identity.Dapper.Samples.Web\Views\Account\Login.cshtml

'SignInManager<CustomUser>' does not contain a definition for 'GetExternalAuthenticationSchemes' and no extension method 'GetExternalAuthenticationSchemes' accepting a first argument of type 'SignInManager<CustomUser>' could be found (are you missing a using directive or an assembly reference?)
Operator '==' cannot be applied to operands of type 'method group' and 'int'
foreach statement cannot operate on variables of type '?' because '?' does not contain a public definition for 'GetEnumerator'

Do you have a working sample uploaded somewhere I can use to test and see how all this works?

**Comment by grandchamp** [comment]
Maybe it's something that changed on 2.0.
I'll try to investigate.

**Comment by Bojanema** [comment]
Yeah, 2.0 had a number of changes, including one in the constructor of I believe either SignInManager or UserManager. Please do let me know once you've resolved this. If not, I can try to find time later on in the week and see if I can contribute.

**Comment by Bojanema** [comment]
@grandchamp just following up, wanted to ask if you have had a chance to take a look?

**Comment by grandchamp** [comment]
Not yet... I'll try to do it today.

**Comment by Bojanema** [comment]
@grandchamp I've had some time to take a look at this and I've come across this article that will show you the changes for identity 2.0

https://github.com/aspnet/Announcements/issues/232

As for the issue of the error above, I've found out that we now need to use GetExternalAuthenticationSchemesAsync instead of GetExternalAuthenticationSchemes

I've tried going further, however, I get No process is on the other end of the pipe.

If I create the database manually (no tables) then that goes away and next thing that happens it fails to create a user with await _userManager.CreateAsync(user, model.Password);

I've tried to figure out why, however, I don't fully understand how your code works here, never seen a scenario like this.

```
 public Task SetPasswordHashAsync(TUser user, string passwordHash, CancellationToken cancellationToken)
        {
            cancellationToken.ThrowIfCancellationRequested();

            if (user == null)
                throw new ArgumentNullException(nameof(user));

            user.PasswordHash = passwordHash;

            return Task.FromResult(0);
        }
```

What exactly gets run here? I can't step into any of this to figure out what function Task.FromResult calls, can't step into that Data layer to get the error.

**Comment by grandchamp** [comment]
I'll take a look now at the sample.

Identity is a bit strange and a bit coupled to EF. The code is full of ```SetXXX``` methods. This methods just updates the User entity, mainly because you have to change the entity properties on EF to make the field updateable when you call ```SubmitChanges```.
```Task.FromResult``` just returns a completed ```Task``` object, because all these method are ```async```, and inside these i don't have a ```await``` operator, so it needs to return a completed task.

**Comment by grandchamp** [comment]
For the database, i don't know which environment do you use for programming, but you can make a Docker container for database (for Docker i prefer PSQL/MySQL), you can take a look on integration tests project Dockerfiles.
https://github.com/grandchamp/Identity.Dapper/blob/master/test/Identity.Dapper.Tests.Integration/MySQL/Dockerfile
https://github.com/grandchamp/Identity.Dapper/blob/master/test/Identity.Dapper.Tests.Integration/PostgreSQL/Dockerfile

**Comment by grandchamp** [comment]
Fixed in https://github.com/grandchamp/Identity.Dapper/commit/7e00457365bbbb787724a5a42fb37e5a955f0962

**Comment by Bojanema** [comment]
@grandchamp I use MSSQL

Also, to create the database and its tables, will the code do it for me like it does in the EF or am I suppose to run some scripts to generate it all, if later, did you provide those scripts somewhere or documentation on what to create that I missed?

**Comment by grandchamp** [comment]
You have to execute the scripts on your DB.
They are on the root of this repo.

MSSQL is possible to run on Docker too.

**Comment by Bojanema** [comment]
To be honest, I've never heard of Docker before. I see your DockerFile for MSSQL, but I have no idea what it does lol.  I'll try to get the website running and tell you how it goes.

**Comment by Bojanema** [comment]
@grandchamp I've tried registering a user and it didn't work. I was also not able to pull any kind of error. The database is created along all of its tables. The connection to the database seems to succeed, but upon calling the creation of the user it fails and it doesn't return any errors as to why it fails.

**Comment by grandchamp** [comment]
Try to debug...
All tests are passing.

**Comment by Bojanema** [comment]
@grandchamp that is what I have been trying to tell you, I can't debug it. I start the debug, I get to the point of when a task result is returned and that is it, there is no error, it just fails. I am not able to debug the data layer to find out what the actual problem is.

Can you tell me how can I step into that data layer to see where the code fails? My problem I think here is that I do not understand your setup. You call `return Task.FromResult(0);` on all of your services. However, I don't get what that actually calls, which function? How is this mapped? How do I debug past that to get an actual error?

As for the tests, do they actually write to the database or they simulate the data layer?

EDIT:

To be more clear:

on AccountController I try to step into this code: `var result = await _userManager.CreateAsync(user, model.Password);`

However, the function I land on is `public Task SetPasswordHashAsync(TUser user, string passwordHash, CancellationToken cancellationToken)` inside DapperUserStore.cs

This just returns fails and after I step out, I go back to the controller which again has false as a result without any errors in the object.

Part of the reason I am trying to make this project work is so I can learn it and understand how it all comes together. I'm rather new to identity and core implementations and I don't fully understand how it comes together. I have been reading all the documentation on identity but I still feel lost when I look at your project. I am lost as to why I can't get an error message that will tell me what is wrong.

**Comment by Bojanema** [comment]
@grandchamp 

I found the issue, I can't believe how small it was. In your SQL scripts, you do not have Address Column. So when I call to register, it crashes. I cannot believe how difficult this was to figure out lol. By difficult I don't mean the problem was hard, but just getting an error message was the hard part. In any case, if you can update that as well it would help prevent future problems.

**Comment by grandchamp** [comment]
I'll take a look on it.

**Comment by grandchamp** [comment]
Above commit fixes it.
Can you confirm?
