### ISSUE TITLE
Wrap Table Names with [ ]

### ISSUE THREAD

**Issue by bagzli** [grandchamp/Identity.Dapper#47]
Hi, I noticed that you don't wrap your table names with [ ]. By that I mean if you query on [dbo].User you will get an error because User is a reserved keyword. However if you query [dbo].[User] then it will work. In any case, I would suggest updating the scripts in the respective projects to wrap those and thus allow people to name their tables however they want without having to change your code too much.

I know you don't have that problem now because you prefixed your table names with Identity, but if I wanted to change those names to my custom names then I will basically rewrite your adapter dlls, but it would be nice not to have to rewrite too much code to make it work and only have to update the variable names where your tables are stored.

**Comment by grandchamp** [comment]
Yes, this behavior is just in SQL Server. The property ```TableFieldNotation``` on ```SqlConfiguration``` it's for this, but it's a single character, and for SQL i have to switch [ for the beggining and ] for the last position. I'll think in something to make this works.

**Comment by bagzli** [comment]
In my case what I did was I rewrote the Identity.Dapper.SqlServer dll. Because I had to change table names, I had to modify this dll, so I just wrote my own as it is a very small dll. When I did that, I simply changed lines of such as this:

`GetUserLoginByLoginProviderAndProviderKeyQuery = "SELECT TOP 1 %USERFILTER% FROM %SCHEMA%.%USERTABLE%, %SCHEMA%.%USERLOGINTABLE% WHERE %SCHEMA%.%USERTABLE%.Id = %SCHEMA%.%USERLOGINTABLE%.UserId AND LoginProvider = %LOGINPROVIDER% AND ProviderKey = %PROVIDERKEY%";`

To look like this

`GetUserLoginByLoginProviderAndProviderKeyQuery = "SELECT TOP 1 %USERFILTER% FROM %SCHEMA%.[%USERTABLE%], %SCHEMA%.%USERLOGINTABLE% WHERE %SCHEMA%.[%USERTABLE%].Id = %SCHEMA%.%USERLOGINTABLE%.UserId AND LoginProvider = %LOGINPROVIDER% AND ProviderKey = %PROVIDERKEY%";`

You could resolve it in such way for your dll too, however, I must admit it would be nice being able to set Table Names outside of your dll in some way. Maybe there is and I missed it?

**Comment by grandchamp** [comment]
You can create a class inheriting from ```SqlServerConfiguration```, or declare a new instance of ```SqlServerConfiguration``` and change RoleTable, UserTable, UserClaimTable, UserRoleTable and UserLoginTable properties values.

**Comment by grandchamp** [comment]
Not really a fix, but https://github.com/grandchamp/Identity.Dapper/commit/34f240c08e8fff45a257f79ac8ee63f415aa22b2 does it for the default tables now. If you want to change your table names on SQL Server, you can do:

```
.AddDapperIdentityFor(new SqlServerConfiguration
{
      RoleTable = "[My Table IdentityRole]",
      UserTable = "[User]";
      UserClaimTable = "[MyIdentityUserClaim]";
      UserRoleTable = "[MyIdentityUserRole]";
      UserLoginTable = "[MyIdentityLogin]";
})
```
