### ISSUE TITLE
SQL Server  - Integrated Security

### ISSUE THREAD

**Issue by sajeshkumaran** [grandchamp/Identity.Dapper#49]
Thank you for all your work which saved a lot of my time. 

It would have been better to have an option to set the SQL database credentials to Integrated windows security. I am not sure if I am asking something wrong since I am pretty new to this Asp.Net Core Api.

Thanks

**Comment by grandchamp** [comment]
Can't you pass UserName and Password empty and change the connection string? Give a try.

**Comment by sajeshkumaran** [comment]
Ok. I will try. Thanks

**Comment by grandchamp** [comment]
It worked?

**Comment by conankid2512** [comment]
I have same problem. I don't think it will work with empty username and password since it throw an exception.

https://github.com/grandchamp/Identity.Dapper/blob/master/src/Identity.Dapper.SqlServer/Connections/SqlServerConnectionProvider.cs

```
if (string.IsNullOrEmpty(_connectionProviderOptions.Value?.ConnectionString))
                throw new ArgumentNullException("There's no DapperIdentity:ConnectionString configured. Please, register the value.");

            if (string.IsNullOrEmpty(_connectionProviderOptions.Value?.Password))
throw new ArgumentNullException("There's no DapperIdentity:Password configured. Please, register the value.");
```

**Comment by grandchamp** [comment]
Fixed on https://github.com/grandchamp/Identity.Dapper/commit/b6d77ebe0d4f2f34df71c1b932e7b42aae9d193b

**Comment by grandchamp** [comment]
@conankid2512 @sajeshkumaran works now?
