### ISSUE TITLE
Table not found in Mysql

### ISSUE THREAD

**Issue by biju-ps** [grandchamp/Identity.Dapper#53]
I am getting a **_"Table Identity.IdentityUser does not exist"_** error when using mysql . My Database Name is DapperIdentityTest .

**Comment by grandchamp** [comment]
Well... you have to change the default schema, right?

**Comment by biju-ps** [comment]
There is no schema in Mysql right ?

**Comment by grandchamp** [comment]
My default scripts are pointing to `identity`.`tablename`. If you changed to DapperIdentityTest you'll have to update the SchemaName property of the MySqlConfiguration to DapperIdentityTest.

**Comment by biju-ps** [comment]
I  created a new configuration as **MyIdentityConfiguration : SqlConfiguration** and removed the  %SCHEMA%. Now the error is gone !!. 

I just following your sample application. I registered a user and able to login. 
Then,I put a **[Authorize]** attribute to the HomeController.  Now I am redirecting to the login page again after the login.
I put a break point on the Index method , and checked the value of _User.Identity.IsAuthenticated_ . It return **false** . What I am missing ?

**Comment by grandchamp** [comment]
Did you put ` app.UseAuthentication();` on `Configure` at `Startup.cs`?

If yes, post your `Startup.cs` here.

**Comment by biju-ps** [comment]
Sorry I missed that .. :(
Worked as expected .. Thank you !!
