### ISSUE TITLE
Can you add a License file?

### ISSUE THREAD

**Issue by HowdyChad** [grandchamp/Identity.Dapper#55]
This looks like a great package. I'd like to know what the license is to know if I can utilize it in my current project. Thanks!

P.S. I'm a big fan of MIT :)

**Comment by grandchamp** [comment]
You can use It without problems.
I have no knowledge on licenses differences, can you make a overview?

**Comment by HowdyChad** [comment]
Here is a good site that talks about the different ones.  https://tldrlegal.com/ I've found MIT to be the most permissive and is what I associate with all of my projects. Simply create a License.txt at the root and paste in the MIT license text and more folks will utilize your nice library!

Actual text of MIT is here:
https://tldrlegal.com/license/mit-license#fulltext

**Comment by grandchamp** [comment]
Done https://github.com/grandchamp/Identity.Dapper/commit/5c1179f5648678b80fc2f4d623589a94925f0a83
