### ISSUE TITLE
Support standard ConnectionString setting and format

### ISSUE THREAD

**Issue by pstatho** [grandchamp/Identity.Dapper#58]
Identity.Dapper should support ConnectionString configuration out of the box. Chances are the project will require a connection to a DB and will use the standard ConnectionString settings. Identity.Dapper should simply re-use that be default instead of having their own ConnectionProvider. 

Identity.Dapper connection information requires that the username and password be added as separate JSON fields in the settings files, while normally the credentials are within the ConnectionString itself as we can see:
https://www.connectionstrings.com/postgresql/
and
https://docs.microsoft.com/en-us/azure/postgresql/connect-csharp

`
string connString =
                String.Format(
                    "Server={0}; User Id={1}; Database={2}; Port={3}; Password={4};",
                    Host,
                    User,
                    DBname,
                    Port,
                    Password);
`

This will allow us to have one ConnectionString for our app and Identity

**Comment by grandchamp** [comment]
Well, internally i use a `ConnectionStringBuilder` provided by the DBMS .NET clients (Eg: `NpgsqlConnectionStringBuilder`). You'll always provide a connection string without the User and Password, and i'll build the connection string and add the User + Password programatically:

```
            var pSqlConnectionBuilder = new NpgsqlConnectionStringBuilder(_connectionProviderOptions.Value.ConnectionString);

            if (!pSqlConnectionBuilder.IntegratedSecurity && string.IsNullOrEmpty(_connectionProviderOptions.Value?.Password))
                throw new ArgumentNullException("There's no DapperIdentity:Password configured. Please, register the value.");
            else
                pSqlConnectionBuilder.Password = pSqlConnectionBuilder.IntegratedSecurity ? string.Empty : _encryptionHelper.TryDecryptAES256(_connectionProviderOptions.Value.Password);

            if (!pSqlConnectionBuilder.IntegratedSecurity && string.IsNullOrEmpty(_connectionProviderOptions.Value?.Username))
                throw new ArgumentNullException("There's no DapperIdentity:Username configured. Please, register the value.");
            else
                pSqlConnectionBuilder.Username = pSqlConnectionBuilder.IntegratedSecurity ? string.Empty : _connectionProviderOptions.Value.Username;
```

If you don't want to provide an user and password, you'll have to add Integrated Security = true on your connection string, this way you could configure User and Password empty on JSON.


Am i understanding right? I don't see any problem at all.

**Comment by pstatho** [comment]
Yes I saw in the source code since I was curious. My point is that most applications that is using Dapper will use the built-in ConnectionString setting of the appsettings.json file such as:
````
"ConnectionStrings": {
  "DefaultConnection": "Server=127.0.0.1;Port=5432;Database=MyDB;User ID=Myuser;Password=MyPassword;"
},
````
to access data from the database. Have Identity use another connection string (in DapperIdentity config section) that points to the same database doesn't make sense. We are repeating DB connection information.

**Comment by grandchamp** [comment]
Added on https://github.com/grandchamp/Identity.Dapper/commit/206727036b9d35846c12fd527be909b64173b1bd

You can do `services.ConfigureDapperConnectionProvider<PostgreSqlConnectionProvider>(Configuration.GetSection("ConnectionStrings"))`
