### ISSUE TITLE
MySQL Implementation

### ISSUE THREAD

**Issue by grandchamp** [grandchamp/Identity.Dapper#6]
Add support for MySQL.

**Comment by grandchamp** [comment]
Waiting for MySQL connector .NET Core version.

**Comment by arkatechs** [comment]
looks like this was finally released this week.  look forward to seeing any updates towards this.  And thank you for the work!
http://dev.mysql.com/doc/relnotes/connector-net/en/connector-net-news-7-0-4.html

**Comment by grandchamp** [comment]
Done in #19.
