### ISSUE TITLE
email stored in uppercase at the mysql database

### ISSUE THREAD

**Issue by eld1887** [grandchamp/Identity.Dapper#64]
hi,
first evrything works very well. Thanks for your work. But if i register a new user, the email is stored in uppercase in the mysql database. it´s a litte bit irritating, if you want to show the email at your spa (or other homepage) and it´s in upperacse.
So my questioin is:
is it only a problem by me or is it "normal" and wanted by you. At the mysql code for the database, i can´t find something that the email should stored in uppercase.

Thanks for your help.

**Comment by grandchamp** [comment]
That's a default behavior from MS Identity.

**Comment by eld1887** [comment]
Ok, thanks for your answer.
