### ISSUE TITLE
NotSupportedException: Store does not implement IRoleClaimStore<TRole>

### ISSUE THREAD

**Issue by DmitrySikorsky** [grandchamp/Identity.Dapper#65]
Hi! Is it possible to assign claims to the roles? So when user logs in, all the claims of his roles are automatically attached to a user. (I want to have permission claims.)

I get the 'NotSupportedException: Store does not implement IRoleClaimStore<TRole>' exception when try to execute next line of code:

`this.roleManager.AddClaimAsync(role, new Claim("Permission", permissionName))`

Also as I can see there are no tables in the database to store claim-role relations.

Thank you for help!

**Comment by grandchamp** [comment]
This method is really not implemented.
Wanna try a pull request for this?

**Comment by DmitrySikorsky** [comment]
@grandchamp could you explain what should I do to support this? Maybe you can show  where and what should I add, so it would be easier to understand your project.

**Comment by grandchamp** [comment]
First of all, i did go to Identity official repo (https://github.com/aspnet/Identity/) and searched for `IRoleClaimStore`.
The search bring me https://github.com/aspnet/Identity/blob/855f7532aeaba3fa65e6ea2502e6b45dca50bab1/src/EF/RoleStore.cs.
They implemented the `IRoleClaimStore` on `RoleStore`. My `DapperRoleStore` just inherits from `IRoleStore`. So, we'll have to inherit from `IRoleClaimStore` too.
This will bring new methods to `DapperRoleStore`, so it'll have new methods accessing `RoleRepository` (https://github.com/grandchamp/Identity.Dapper/blob/master/src/Identity.Dapper/Repositories/Contracts/IRoleRepository.cs and https://github.com/grandchamp/Identity.Dapper/blob/master/src/Identity.Dapper/Repositories/RoleRepository.cs).
Those new methods on `RoleRepository` will have new queries (https://github.com/grandchamp/Identity.Dapper/tree/master/src/Identity.Dapper/Queries/Role).
Those queries will have new properties on `SqlConfiguration` (https://github.com/grandchamp/Identity.Dapper/blob/master/src/Identity.Dapper/Models/SqlConfiguration.cs) and each of DBMS repos (MySQL, SQL Server and PSQL) will have the real queries on it classes that inherits `SqlConfiguration`.

If you take a look on how it's done today you'll understand.

**Comment by DmitrySikorsky** [comment]
Thank you! Will look at it.

**Comment by grandchamp** [comment]
Feel free to question anything.

**Comment by devalot76** [comment]
@grandchamp This means the next version will have this feature?

**Comment by grandchamp** [comment]
Yes.
@DmitrySikorsky will help us here.

**Comment by DmitrySikorsky** [comment]
I didn't promise :) Will see. I have to discuss it with my client.

**Comment by grandchamp** [comment]
Fixed in #69

**Comment by DmitrySikorsky** [comment]
Wow, is it already in NuGet?

**Comment by grandchamp** [comment]
Yes, It is! 😁

**Comment by DmitrySikorsky** [comment]
Thank you!
