### ISSUE TITLE
Environment.OSVersion

### ISSUE THREAD

**Issue by bagzli** [grandchamp/Identity.Dapper#73]
When you update your project to the latest libraries, you will find that Environment.OSVersion is now deprecated. This project seems to use it in QueryList class.

`var platform = Environment.OSVersion.Platform.ToString();`

**Comment by grandchamp** [comment]
Wanna make a pull request for this?

**Comment by grandchamp** [comment]
@bagzli which package this was updated? I'm not seeing anything.

**Comment by bagzli** [comment]
When you upgrade core to 2.1.0-preview1-final. What happened to me after I downloaded your source code and upgraded everything to the latest, I got deprecation error when I tried to compile.

**Comment by grandchamp** [comment]
Oh, ok.
I didn't update yet because 2.1 is preview, when they release the final version i'll take a look at it.
Thanks.

**Comment by bagzli** [comment]
No problem, I upgraded to test and see what bugs I can expect and this was one of them as I can't even compile the project because of this.
