### ISSUE TITLE
How to use string Id for dapper identity user?

### ISSUE THREAD

**Issue by dango85** [grandchamp/Identity.Dapper#76]
I am having hard time using string type for user id in custom user store. The code breaks at Activator.CreateInstance for idProperty under GetColumns method. Line number 32 om ColumnsBuilderExtensions.cs. On doing some research it is basically caused because System.String does not have a default constructor. Do have any suggestion around how to use string type id's using your your library?

**Comment by grandchamp** [comment]
Sorry for never have answered your question. Maybe it's something that we could work, never tried to use string (just GUID). Do you want to make a pull request for this?

**Comment by dango85** [comment]
![image](https://user-images.githubusercontent.com/5007593/43437956-54dcfb62-9451-11e8-9cc3-ab873e72dea6.png)

Attached is the work around that I added to handle strings.
